"""Add entity column to User model

Revision ID: c3c9ef75dbb3
Revises: 6ec2902321a9
Create Date: 2025-05-21 18:16:44.440458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c9ef75dbb3'
down_revision = '6ec2902321a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity', sa.String(length=100), nullable=False, server_default='default_entity'))
    op.execute("ALTER TABLE users ALTER COLUMN entity DROP DEFAULT")  # Remove default after migration
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('entity')

    # ### end Alembic commands ###
